# Generated by Django 2.2.12 on 2020-09-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=1)),
                ('phoneinterview', models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=1)),
                ('test', models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=1)),
                ('offer', models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=1)),
                ('denied', models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Company')),
            ],
        ),
    ]
