# Generated by Django 3.0 on 2020-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='denied',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='offer',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='phoneinterview',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='response',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='test',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
    ]
