# Generated by Django 3.0 on 2020-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200924_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='denied',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='offer',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='phoneinterview',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='response',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='test',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='NO', max_length=20),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
