# Generated by Django 3.0 on 2020-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200925_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='response',
            field=models.IntegerField(choices=[(1, 'Y'), (0, 'N')], default='NO'),
        ),
    ]
